services:
  - type: web
    name: invoice-generator-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn asgi:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  - name: invoice-frontend
    type: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
